"""empty message

Revision ID: 04cb9e0f450e
Revises: 8baef2ae989b
Create Date: 2021-10-10 12:43:12.274592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04cb9e0f450e'
down_revision = '8baef2ae989b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flatprice_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('town', sa.String(length=64), nullable=True),
    sa.Column('flatType', sa.String(length=64), nullable=True),
    sa.Column('floorArea', sa.Integer(), nullable=True),
    sa.Column('storey', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('town_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('town', sa.String(length=64), nullable=True),
    sa.Column('flatType', sa.String(length=64), nullable=True),
    sa.Column('floorArea', sa.Integer(), nullable=True),
    sa.Column('storey', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('town_input')
    op.drop_table('flatprice_input')
    # ### end Alembic commands ###
