"""empty message

Revision ID: 42ec2961c3df
Revises: ce6dd7ec57d2
Create Date: 2021-10-14 15:43:43.315091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ec2961c3df'
down_revision = 'ce6dd7ec57d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('town_input', 'town')
    op.drop_column('town_input', 'OUTPUT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_input', sa.Column('OUTPUT', sa.INTEGER(), nullable=True))
    op.add_column('town_input', sa.Column('town', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
