"""empty message

Revision ID: 869e02fbf42b
Revises: 04cb9e0f450e
Create Date: 2021-10-10 17:38:28.470865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869e02fbf42b'
down_revision = '04cb9e0f450e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('town_input', 'town')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_input', sa.Column('town', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
