"""empty message

Revision ID: c75eefa31412
Revises: d0c2be627fb9
Create Date: 2021-10-10 20:10:20.468731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c75eefa31412'
down_revision = 'd0c2be627fb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_input', sa.Column('OUTPUT1', sa.String(length=64), nullable=True))
    op.add_column('town_input', sa.Column('OUTPUT2', sa.String(length=64), nullable=True))
    op.add_column('town_input', sa.Column('OUTPUT3', sa.String(length=64), nullable=True))
    op.drop_column('town_input', 'OUTPUT')
    op.drop_column('town_input', 'town')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_input', sa.Column('town', sa.VARCHAR(length=64), nullable=True))
    op.add_column('town_input', sa.Column('OUTPUT', sa.INTEGER(), nullable=True))
    op.drop_column('town_input', 'OUTPUT3')
    op.drop_column('town_input', 'OUTPUT2')
    op.drop_column('town_input', 'OUTPUT1')
    # ### end Alembic commands ###
