"""empty message

Revision ID: ce6dd7ec57d2
Revises: c75eefa31412
Create Date: 2021-10-14 15:39:02.840974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6dd7ec57d2'
down_revision = 'c75eefa31412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('town_input', 'OUTPUT')
    op.drop_column('town_input', 'town')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_input', sa.Column('town', sa.VARCHAR(length=64), nullable=True))
    op.add_column('town_input', sa.Column('OUTPUT', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
