"""empty message

Revision ID: f01bdda75e70
Revises: 42ec2961c3df
Create Date: 2021-10-18 11:04:36.671795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01bdda75e70'
down_revision = '42ec2961c3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_input', sa.Column('budget', sa.Integer(), nullable=True))
    op.drop_column('town_input', 'OUTPUT')
    op.drop_column('town_input', 'town')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town_input', sa.Column('town', sa.VARCHAR(length=64), nullable=True))
    op.add_column('town_input', sa.Column('OUTPUT', sa.INTEGER(), nullable=True))
    op.drop_column('town_input', 'budget')
    # ### end Alembic commands ###
